name: Deploy to prod

on:
  push:
    branches:
      - feat/deploy-to-prod
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Make production envfile
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_VITE_API_URL: ${{ secrets.API_URL }}
          file_name: .env.local

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      # Sync files via FTP
      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          password: ${{ secrets.REMOTE_PASSWORD }}
